name = "sg-do" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
[[routes]]
pattern = "sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.vcip.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "business.blibli.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.sg-do.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.vcip.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "business.blibli.com.sg-do.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.sg-do.ndeso.web.id"
custom_domain = true


[vars]
PROXYIP = "178.128.80.43:443"
# "54.251.167.101"
 # 35.219.15.90 ID
 # 51.79.254.182
 # 35.219.50.99 ID
 # 175.142.86.195
 # 210.186.12.244
 # 166.88.35.141
 # 172.232.238.169  london
 # 54.251.167.101 
UUID = "d2eed70a-4102-42b0-8b40-279e6d901a02"
#36d47e1e-1f4d-420b-93f0-dadb5e5d2d97,e308f673-f15d-4633-90f8-18438bab3c4f,d92417b6-0aa0-423c-93ad-179a51c88200"
# d2eed70a-4102-42b0-8b40-279e6d901a02
# 36d47e1e-1f4d-420b-93f0-dadb5e5d2d97
# e308f673-f15d-4633-90f8-18438bab3c4f
# d92417b6-0aa0-423c-93ad-179a51c88200
